ecosystem/accounts/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import LogIn_View, LogOut_View, Registration_View

app_name = 'accounts'

urlpatterns = [
    path('login/', LogIn_View.as_view(), name='login'),
    path('logout/', LogOut_View.as_view(), name='logout'),
    path('registration/', Registration_View.as_view(), name='registration'),
]

ecosystem/ecosystem/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

import journal, accounts, warehouse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('journal/', include('journal.urls', namespace='journal')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('warehouse/', include('warehouse.urls', namespace='warehouse'))
]

ecosystem/journal/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'journal'

urlpatterns = [
    path('LK/student/<str:slug>/<str:type_of_week>', views.LK_student_View.as_view(), name='LK_student'),
    path('LK/teacher/<str:slug>/<str:type_of_week>', views.LK_teacher_View.as_view(), name='LK_teacher'),
]

ecosystem/journal/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
from django.conf import settings
from django.utils.text import slugify

import datetime



class School_subject(models.Model):

    name = models.CharField(max_length = 150)
    
    def __str__(self):
        return self.name

ecosystem/journal/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.views.generic import DetailView, ListView, TemplateView

from accounts.models import Student, Teacher
from  accounts.week_type import Week_type


class LK_student_View(TemplateView):

    model = Student
    template_name = 'journal/index.html'
    queryset = Student.objects.all()

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated == True:
            if self.kwargs['type_of_week'] != Week_type.type_of_week():
                return redirect(f"/journal/LK/student/{self.kwargs['slug']}/{Week_type.type_of_week()}")
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)
        else:
            return redirect("/accounts/login/")


    def get_context_data(self, **kwargs):
        
        DAY_CHOICES = {
            'M':'Понедельник',
            'Tu':'Вторник',
            'W':'Среда',
            'Th':'Четверг',
            'F':'Пятница',
        }

        TYPE_CHOICES = {
            'NUM':'Числитель',
            'DEN':'Знаменатель',
        }
             
        schedule = {}

        slug = self.kwargs['slug']
        type_of_week = self.kwargs['type_of_week']
        context = super().get_context_data(**kwargs)
        user_data = Student.objects.get(slug=slug.lower())
        group_data = user_data.group.all()

        for group in group_data:
            bufer = []
            if type_of_week == group.week_type:
                bufer.append(DAY_CHOICES[group.day])
                bufer.append(group.start_time)
                bufer.append(group.end_time)
                bufer.append(group.auditorium)
                schedule[group.school_subject.name] = bufer

        context['schedule'] = schedule
        context['user_data'] = user_data
        context['week_type'] = TYPE_CHOICES[type_of_week]

        return context


class LK_teacher_View(TemplateView):

    model = Student
    template_name = 'index.html'
    queryset = Student.objects.all()

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated == True:
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)
        else:
            return redirect("/accounts/login/")

    def get_context_data(self, **kwargs):
        slug = self.kwargs['slug']
        context = super().get_context_data(**kwargs)
        user_data = Teacher.objects.get(slug=slug)

        context['user_data'] = user_data

        return context

ecosystem/journal/templates/journal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Эксистема ДТ/ЦТПО</title>
    <link href="{% static 'journal/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static 'journal/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>


{% block content %}{% endblock %}

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Сделал &copy; Никита Швора 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Вы уверены?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Нажмите "Выйти", для выхода из системы</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Отмена</button>
                    <a class="btn btn-primary" href="{% url 'accounts:logout' %}">Выйти</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'journal/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'journal/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'journal/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'journal/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'journal/vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'journal/js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'journal/js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>