ecosystem/ecosystem/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

import journal, accounts, warehouse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('journal/', include('journal.urls', namespace='journal')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('warehouse/', include('warehouse.urls', namespace='warehouse'))
]

ecosystem/journal/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'journal'

urlpatterns = [
    path('LK/student/<str:slug>/<str:type_of_week>', views.LK_student_View.as_view(), name='LK_student'),
    path('LK/teacher/<str:slug>/<str:type_of_week>', views.LK_teacher_View.as_view(), name='LK_teacher'),
]

ecosystem/warehouse/urls.py
from unicodedata import name
from django.contrib.auth import views
from django.urls import path

# from ecosystem.warehouse.models import Category
from .views import Home, Catalog, SearchResultsView

app_name = 'warehouse'

urlpatterns = [
    path('', Home.as_view(), name='warehouse'),
    path('search/',SearchResultsView.as_view(), name='search_product'),
    path('<str:slug>/', Catalog.as_view(), name='render_catalog'),
]

ecosystem/journal/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
from django.conf import settings
from django.utils.text import slugify

import datetime



class School_subject(models.Model):

    name = models.CharField(max_length = 150)
    
    def __str__(self):
        return self.name

ecosystem/warehouse/models.py
from django.db import models
from django.utils import timezone
# from django.contrib.auth.models import User
from accounts.models import Teacher
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=256, db_index=True)
    slug = models.SlugField(max_length=256, unique=True)

    def __str__(self):
        return self.name

class Warehouse(models.Model):
    category = models.ForeignKey(Category,
                                related_name='products',
                                on_delete=models.CASCADE,
                                null=True)
    name = models.CharField(max_length=256, db_index=True)
    slug = models.SlugField(max_length=256, db_index=True, null=True)
    cell = models.CharField(max_length=128)
    remains = models.IntegerField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

class Extradition(models.Model):
    # category = models.ForeignKey(Category,
    #                             related_name='products',
    #                             on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    cell = models.CharField(max_length=128)
    quantity = models.IntegerField()
    data = models.DateTimeField()
    user_id = models.ManyToManyField(
        Teacher,
        related_name='extradition'
    )

# class Shipment(models.Model):
#     name = models.CharField(max_length=128)
#     type = models.CharField(max_length=128)
#     cell = models.CharField(max_length=128)
#     quantity = models.IntegerField()
#     data = models.DateField()

ecosystem/journal/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.views.generic import DetailView, ListView, TemplateView

from accounts.models import Student, Teacher
from  accounts.week_type import Week_type


class LK_student_View(TemplateView):

    model = Student
    template_name = 'journal/index.html'
    queryset = Student.objects.all()

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated == True:
            if self.kwargs['type_of_week'] != Week_type.type_of_week():
                return redirect(f"/journal/LK/student/{self.kwargs['slug']}/{Week_type.type_of_week()}")
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)
        else:
            return redirect("/accounts/login/")


    def get_context_data(self, **kwargs):
        
        DAY_CHOICES = {
            'M':'Понедельник',
            'Tu':'Вторник',
            'W':'Среда',
            'Th':'Четверг',
            'F':'Пятница',
        }

        TYPE_CHOICES = {
            'NUM':'Числитель',
            'DEN':'Знаменатель',
        }
             
        schedule = {}

        slug = self.kwargs['slug']
        type_of_week = self.kwargs['type_of_week']
        context = super().get_context_data(**kwargs)
        user_data = Student.objects.get(slug=slug.lower())
        group_data = user_data.group.all()

        for group in group_data:
            bufer = []
            if type_of_week == group.week_type:
                bufer.append(DAY_CHOICES[group.day])
                bufer.append(group.start_time)
                bufer.append(group.end_time)
                bufer.append(group.auditorium)
                schedule[group.school_subject.name] = bufer

        context['schedule'] = schedule
        context['user_data'] = user_data
        context['week_type'] = TYPE_CHOICES[type_of_week]

        return context


class LK_teacher_View(TemplateView):

    model = Student
    template_name = 'index.html'
    queryset = Student.objects.all()

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated == True:
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)
        else:
            return redirect("/accounts/login/")

    def get_context_data(self, **kwargs):
        slug = self.kwargs['slug']
        context = super().get_context_data(**kwargs)
        user_data = Teacher.objects.get(slug=slug)

        context['user_data'] = user_data

        return context

ecosystem/warehouse/views.py
from pyexpat import model
from unicodedata import name
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.db.models import Q
from django.urls import resolve

from .form import Order

from django.views.generic import DetailView, ListView, TemplateView
from warehouse.models import Warehouse, Category
from accounts.models import Teacher

# Create your views here.
class Home(TemplateView):

    template_name = 'warehouse/index.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        category = Category.objects.all()
        users = User.objects.all()
        # teacher = Teacher.objects.all()
        # print(teacher)
        print(users)
        form = Order()
        context['form'] = form

        context['catalog_list'] = category
        context['products'] = Warehouse.objects.all()
        context['user'] = users
        context['url'] = resolve(self.request.path_info).url_name
        
        print(context)
        return context

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated == True:
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed
            return handler(request, *args, **kwargs)
        else:
            return render(request, "/accounts/login/")

class Catalog(TemplateView):
    
    template_name = 'warehouse/index.html'

    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        category_list = Category.objects.all()
        products = Category.objects.get(slug = self.kwargs['slug']).products.all()
        # print(products)

        context['catalog_list'] = category_list
        context['products'] = products
        
        print(context)

        return context


class SearchResultsView(ListView):
    model = Warehouse
    template_name = 'warehouse/index.html'


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        category_list = Category.objects.all()
        # print(context)
        context['catalog_list'] = category_list
        context['url'] = resolve(self.request.path_info).url_name
        print(context)

        return context


    def get_queryset(self):
        query = self.request.GET.get('search')
        print(query)
        # products = Category.objects.all().product.all()
        # print(products)
        object_list = Warehouse.objects.filter(Q(name__icontains=query) | Q(cell__icontains=query))
        print(object_list)
        
        return object_list

    

ecosystem/journal/templates/warehouse/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'warehouse/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'warehouse/css/warehouse.css' %}" >

    <title>ДТ/ЦТПО Склад</title>
</head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand nav-link" href="{% url 'warehouse:warehouse' %}">Склад</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="col-xl-12">
                    <div class="navbar-nav justify-content-end">
                        <!-- {#{%if status == 'admin'%}#} -->
                            {#<a class="nav-item nav-link" href="{{url_for('index')}}">{{ navigation[0] }}<span class="sr-only">(current)</span></a>#}
                            {#<a class="nav-item nav-link" href="{{url_for('log')}}">{{ navigation[1] }}</a>#}
                            {#<a class="nav-item nav-link" href="{{url_for('register')}}">{{ navigation[2] }}</a>#}
                            {#<a class="nav-item nav-link" href="{{url_for('logout')}}">{{ navigation[3] }}</a>#}
                        <!-- {#{%elif status == 'client'%}#} -->
                            <form action="{% url 'warehouse:search_product' %}" method="get">
                                <input name="search" type="text" class="form-control" placeholder="Поиск...">
                            </form>
                            <a class="nav-item nav-link" href="">Почта<span class="sr-only">(current)</span></a>
                            <a class="nav-item nav-link" href="https://t.me/Prom1x_test_bot?start={{name_user}}">Телега</a>
                            <a class="nav-item nav-link" href="">Вернуться в журнал</a>
                        <!-- {#{%endif%}#} -->
                    </div>
                </div>
            </div>
        </nav>
        {% block content %}{% endblock %}
    </body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Подключаем Bootstrap JS -->
    <script src="{% static 'warehouse/js/post_script.js' %}"></script> 
    <script src="{% static 'warehouse/js/bootstrap.min.js' %}"></script>
</html>

ecosystem/journal/templates/warehouse/index.html
{% extends "warehouse/base.html" %}

{% block content %}
    <div class="catalog">
        <div class="row">
            <div class="col-xl-2 desktops">
            {% for item in catalog_list%}
                <p>
                    <a class="btn btn-primary btn-block" href="{% url 'warehouse:render_catalog' item.slug%}">
                        {{item.name}}
                    </a>
                </p>
            {% endfor %}
            </div>
            <div class="col-xl-12 phones">
                    <a class="btn btn-primary col-xl-12 margin_bot" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                        Категории
                    </a>
                <div class="collapse" id="collapseExample">
                    <div class="card card-body">
                    {% for item in catalog_list %}

                        <p>
                            <a class="btn btn-primary btn-block" href="{% url 'warehouse:render_catalog' item.slug%}">
                                {{item.name}}
                            </a>
                        </p>
                    {% endfor %}
                    </div>
                </div>
            </div>
            <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="phones">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse" id="navbar">
                        <div class="card card-body">
                        {% for item in category %}
                            <p>
                                <a  onclick="send_post('{{item}}')" class="btn btn-primary btn-block" data-toggle="collapse" href="#" role="button" aria-expanded="false" aria-controls="collapseExample">
                                    {{item}}
                                </a>
                            </p>
                        {% endfor %}
                        </div>
                    </div>
                </div>
            </nav> -->
            <div class="col scroll">
                <div class="bd-example">
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="exampleModalLabel">Заказ</h4>
                            </div>
                            <div class="modal-body">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{ form.product_name }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.quantity }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.massage_text }}
                                    </div>
                                    <button type="submit">Добавить</button>
                                </form>
                                
                                <div class="modal-footer" id="modal_window">        
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                 <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="editModalLabel">Изменение товара</h4>
                            </div>
                            <div class="modal-body">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{ form.product_name }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.quantity }}
                                    </div>
                                    <button type="submit">Добавить</button>
                                </form>
                                
                                <div class="modal-footer" id="modal_window">        
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-dark">
                    <thead>
                        <tr class="tab_col">
                        
                                <th scope="col">Название</th>
                                <th scope="col">Ячейка</th>
                                <th scope="col">Остаток</th>
                                <th scope="col">Действие</th>

                        </tr>
                    </thead>
                    <tbody id='table_info'>
                        {% if url == 'search_product' %}
                            {% for item in object_list %}
                                <tr class="tab_col">
                                    <th scope="col">{{item.name}}</th>
                                    <th scope="col">{{item.cell}}</th>
                                    <th scope="col">{{item.remains}}</th>
                                    <th scope="col" id="{{item.name}}">
                                        {# % if % #}
                                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Заказать</button>
                                    </th>
                                </tr>
                            {% endfor %}
                        {% else %}
                            {% for item in products %}
                                <tr class="tab_col">
                                    <th scope="col">{{item.name}}</th>
                                    <th scope="col">{{item.cell}}</th>
                                    <th scope="col">{{item.remains}}</th>
                                    <th scope="col">
                                        <button type="button" class="btn btn-primary" id="{{item.id}}" data-toggle="modal" data-target="#exampleModal">Заказать</button>
                                    </th>
                                </tr>
                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}